@startuml

actor Пользователь as User

box Прикладной сервис
    participant Sleep as "Основной контейнер"
    participant Sidecar
end box 


participant External as "Внешний сервис"

autonumber

User->Sleep++: kubectl exec \ \n"$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})" \ \n-c sleep -- curl -svS http://my-nginx.mesh-external.svc.cluster.local:443
    Sleep->Sidecar++: HTTP GET \n my-nginx.mesh-external.svc.cluster.local:443
        Sidecar->External++: HTTP GET \n my-nginx.mesh-external.svc.cluster.local:443
        return status 400
    return status 400
return